name: fastp ci
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-12
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout scm
        uses: actions/checkout@v3

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: install build dependencies (Ubuntu)
        run: sudo apt update && sudo apt install -y build-essential nasm
        if: runner.os == 'Linux'

      - name: install build dependencies (MacOS)
        run: brew install automake autoconf coreutils nasm
        if: runner.os == 'macOS'

      
      - name: install build dependencies (Windows)
        run: choco install make nasm strawberryperl --yes
        if: runner.os == 'Windows'  

      - name: get deflate
        uses: actions/checkout@v3
        with:
          repository: ebiggers/libdeflate
          path: src/libs/deflate
          ref: v1.22


      - name: build deflate
        run: |
          cd src/libs/deflate
          cmake -B build
          cmake --build build -j ${{ steps.cpu-cores.outputs.count }}
          sudo cmake --install build
          cd -
        if: runner.os != 'Windows'

      - name: build deflate (Windows)
        run: |
          cd src/libs/deflate
          cmake -B build -DCMAKE_INSTALL_PREFIX=C:\install
          cmake --build build --parallel
          cmake --install build
          cd ..
        if: runner.os == 'Windows'

      - name: build isa-l
        run: |
          cd src/libs/isa-l
          ./autogen.sh
          ./configure --prefix=/usr/local
          make -j ${{ steps.cpu-cores.outputs.count }}
          sudo make install
          cd -
        if: runner.os != 'Windows'

      - name: build isa-l (Windows)
        run: |
          cd src/libs/isa-l
          bash -c "./autogen.sh && ./configure && make -j $(nproc)"
          cd ..
        shell: bash
        if: runner.os == 'Windows'

      - name: make fatsp  (MacOS)
        run: bash -c 'make -j $(nproc)'
        if: runner.os == 'macOS'

      - name: make fastp static (Ubuntu)
        run: bash -c 'make -j $(nproc) static'
        if: runner.os == 'Linux'

      - name: make fastp (Windows)
        run: bash -c 'make -j $(nproc) static'
        shell: bash
        if: runner.os == 'Windows'  

      - name: test
        run: chmod a+x ./fastp && ./fastp --version
